language: android

jdk: oraclejdk8
# Turn off caching to avoid any caching problems
cache: false
sudo: false

addons:
  apt:
    packages:
      - build-essential
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - cmake
      - aria2
      - ant
      - lib32stdc++6
      - lib32z1
      - lib32z1-dev
      - lib32bz2-1.0

cache:
  - apt
  - ccache

android:
  components:
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support

script:
  - "./gradlew assembleDebug"

before_script:
 - mkdir -p "$ANDROID_HOME/licenses"
 - cp ./android-sdk-license "$ANDROID_HOME/licenses/"

notifications:
  email:
    recipients:
      - tornaco@163.com
    on_success: always # default: change
    on_failure: always # default: always
  
