language: android

jdk: oraclejdk8
# Turn off caching to avoid any caching problems
cache: false
sudo: false

android:
  components:
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support

script:
  - "./gradlew assembleDebug"
